#!/usr/bin/env bash
# Install HAProxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get -y install haproxy=2.8.\*

# Configure HAproxy so that it send traffic to web-01 and web-02
printf "\nbackend web-backend
	balance roundrobin
	server 349756-web-01 35.175.104.84:80 check
	server 349756-web-02 100.26.151.210:80 check

frontend http
	bind *:80
	mode http
	
	default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

# Start haproxy
sudo service haproxy start
